language: node_js
node_js:
  - '0.6'
  - '0.8'
  - '0.10'
  - '0.12'
  - '1.0'
  - '1.8'
  - '2.0'
  - '2.5'
  - '3.0'
  - '3.3'
  - '4.0'
  - '4.2'

matrix:
  include:
    - node_js: '4.2'
      env: MYSQL_TYPE=mariadb MYSQL_HOST=localhost MYSQL_DATABASE=orz_test MYSQL_USER=root MYSQL_PASSWORD=
      addons: {mariadb: '10.1'}

sudo: false


before_script:
- "mysql -e 'create database orz_test; select version();'"

script:
  # Run test script, depending on istanbul install
  - "npm test"

after_script:
  # - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

env:
  - MYSQL_TYPE=mysql MYSQL_HOST=localhost MYSQL_DATABASE=orz_test MYSQL_USER=root MYSQL_PASSWORD=

mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: node_mysql