#!/bin/bash
ROOT=`dirname $0`
$ROOT/node_modules/.bin/istanbul cover \
$ROOT/node_modules/.bin/_mocha -- \
                          --timeout 10000 \
                          --reporter spec \
                          --require $ROOT/test/init.js \
                          $ROOT/test/**/*.test.js